### ISSUE TITLE
dart link not working

### ISSUE THREAD

**Issue by azrafe7** [damoebius/HaxeBench#3]
Console reports a size of 0 and refuses to load it (although it's there). Maybe some error parsing it? not sure.

win 8, chrome 66.

**Comment by damoebius** [comment]
Well, it's quite strange and you aren't the first with that problem.
But it works for me on desktop and mobile.
Actually I committed the dart2 minified version. I'll try with dart 1

**Comment by damoebius** [comment]
It works

**Comment by azrafe7** [comment]
Still doesn't for me :|

![image](https://user-images.githubusercontent.com/1266447/40929529-4fd42bca-6825-11e8-8805-667cadee7813.png)
